"""
Compass driver supporting QMC5883L and HMC5883L.
Includes corrected declination handling, improved QMC detection,
and fault-tolerant I²C access.
"""

import os
import fcntl
import ctypes
import json
import math
import time
import logging

try:
    from smbus2 import SMBus, i2c_msg
except Exception:
    from smbus import SMBus
    i2c_msg = None


logger = logging.getLogger("compass")

# Default path to the correction table generated by compass_diagnostic.py
_CORRECTION_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "calibration", "compass_correction.json"
)


def deg_to_rad(deg: float) -> float:
    """Convert degrees to radians."""
    return deg * math.pi / 180.0


class Compass:
    def __init__(self, bus=1, declination_deg=-0.5, config=None):
        self.bus = SMBus(bus)
        self._bus_num = bus
        self.address = None
        self.chip = None
        self._qmc_variant = None  # "L" for 5883L, "P" for 5883P
        self._qmc_recovered_once = False

        # declination stored in radians
        self.declination = deg_to_rad(declination_deg)

        # --- Calibration offsets (loaded from config or defaults) ---
        # Hard-iron:  centres the raw ellipse at (0,0)
        # Soft-iron:  scales the axes so the ellipse becomes a circle
        # Heading offset: rotates 0° to align with magnetic North
        cal = (config or {}).get('compass', {})
        self._cal_offset_x = float(cal.get('offset_x', 0.0))
        self._cal_offset_y = float(cal.get('offset_y', 0.0))
        self._cal_scale_x  = float(cal.get('scale_x', 1.0))
        self._cal_scale_y  = float(cal.get('scale_y', 1.0))
        self._cal_heading_offset = float(cal.get('heading_offset', 0.0))
        self._calibrated = bool(cal.get('calibrated', False))
        if self._calibrated:
            logger.info(f"Compass calibration loaded: offset=({self._cal_offset_x:.1f}, "
                        f"{self._cal_offset_y:.1f}), scale=({self._cal_scale_x:.4f}, "
                        f"{self._cal_scale_y:.4f}), heading_offset={self._cal_heading_offset:.1f}°")

        # Try raw fd for ioctl fallback
        try:
            fd = getattr(self.bus, "fd", None)
            if isinstance(fd, int) and fd >= 0:
                self._raw_i2c_fd = fd
            else:
                raise Exception("no fd")
        except Exception:
            try:
                self._raw_i2c_fd = os.open(f"/dev/i2c-{bus}", os.O_RDWR)
            except Exception:
                self._raw_i2c_fd = None

        # common magnetometer addresses
        addresses = [0x0D, 0x0C, 0x2C, 0x1E]
        for addr in addresses:
            try:
                self.bus.read_byte_data(addr, 0x00)
                self.address = addr
                break
            except Exception:
                continue

        if self.address is None:
            raise Exception("Compass not found on I2C bus.")

        self.chip = self._detect_chip_type(self.address)

        if self.chip in ("QMC5883L", "QMC5883P"):
            self._qmc_init()
        else:
            # classic HMC configuration
            self._write_reg(0x00, 0x70)  # averaging, rate, normal
            self._write_reg(0x01, 0x20)  # gain
            self._write_reg(0x02, 0x00)  # continuous

        # --- Load compass correction table (magnetic → true) ---
        self._correction = self._load_correction()

    # --------------------------------------------------------------
    # Compass correction (magnetic → true heading)
    # --------------------------------------------------------------
    @staticmethod
    def _load_correction():
        """Load compass_correction.json generated by compass_diagnostic.py.

        Returns dict with 'type' ('none'|'constant'|'lookup_table') and
        associated data, or a safe no-op dict if file missing/invalid.
        """
        try:
            if os.path.exists(_CORRECTION_FILE):
                with open(_CORRECTION_FILE, "r") as f:
                    data = json.load(f)
                ctype = data.get("type", "none")
                if ctype == "constant":
                    logger.info("Compass correction loaded: CONSTANT offset %+.1f°",
                                data.get("offset", 0))
                    return data
                elif ctype == "lookup_table":
                    table = data.get("table", [])
                    logger.info("Compass correction loaded: LOOKUP TABLE (%d entries)",
                                len(table))
                    return data
                else:
                    logger.info("Compass correction file present but type='%s' — no correction", ctype)
                    return {"type": "none"}
            else:
                logger.info("No compass correction file — using declination-only heading until a diagnostic table is created")
                return {"type": "none"}
        except Exception as e:
            logger.warning("Failed to load compass correction: %s", e)
            return {"type": "none"}

    def get_correction_data(self):
        """Return the loaded correction dict (for serving to dashboard)."""
        return dict(self._correction)

    def apply_correction(self, magnetic_heading):
        """Apply correction to convert magnetic heading → true heading.

        This is the core mapping used by the True North compass.
        """
        ctype = self._correction.get("type", "none")

        if ctype == "none":
            return magnetic_heading

        if ctype == "constant":
            offset = self._correction.get("offset", 0.0)
            return (magnetic_heading - offset) % 360.0

        if ctype == "lookup_table":
            return self._apply_lookup_table(magnetic_heading)

        return magnetic_heading  # unknown type — pass through

    def _apply_lookup_table(self, magnetic_heading):
        """Lookup-table correction with linear interpolation and 0°/360° wrap."""
        table = self._correction.get("table", [])
        if not table:
            return magnetic_heading

        n = len(table)
        mag = magnetic_heading % 360.0

        # Find bracketing entries (table sorted by magnetic ascending)
        lower_idx = None
        upper_idx = None
        for i in range(n):
            if table[i]["magnetic"] <= mag:
                lower_idx = i
            if table[i]["magnetic"] >= mag and upper_idx is None:
                upper_idx = i

        # Wrap-around cases
        if lower_idx is None:
            lower_idx = n - 1
        if upper_idx is None:
            upper_idx = 0

        if lower_idx == upper_idx:
            correction = table[lower_idx]["correction"]
        else:
            m1 = table[lower_idx]["magnetic"]
            m2 = table[upper_idx]["magnetic"]
            c1 = table[lower_idx]["correction"]
            c2 = table[upper_idx]["correction"]

            # Handle wrap-around
            if m2 < m1:
                m2 += 360.0
            mag_adj = mag if mag >= m1 else mag + 360.0

            span = m2 - m1
            if span == 0:
                correction = c1
            else:
                t = (mag_adj - m1) / span
                diff = c2 - c1
                while diff > 180:
                    diff -= 360
                while diff < -180:
                    diff += 360
                correction = c1 + t * diff

        return (magnetic_heading - correction) % 360.0

    # --------------------------------------------------------------
    # Detection
    # --------------------------------------------------------------
    def _detect_chip_type(self, addr):
        try:
            ida = self.bus.read_byte_data(addr, 0x0A)
            idb = self.bus.read_byte_data(addr, 0x0B)
            idc = self.bus.read_byte_data(addr, 0x0C)
            if bytes([ida, idb, idc]) == b"H43":
                return "HMC5883L"
        except Exception:
            pass

        if addr in (0x0D, 0x0C):
            self._qmc_variant = "L"
            return "QMC5883L"

        if addr in (0x2C, 0x2A):
            try:
                chip_id = self.bus.read_byte_data(addr, 0x00)
            except Exception:
                chip_id = None

            if chip_id == 0x80 or addr == 0x2A:
                self._qmc_variant = "P"
                return "QMC5883P"

            self._qmc_variant = "L"
            return "QMC5883L"
        return "HMC5883L"

    # --------------------------------------------------------------
    # Register read/write
    # --------------------------------------------------------------
    def _write_reg(self, reg, val):
        self.bus.write_byte_data(self.address, reg & 0xFF, val & 0xFF)

    def _read_reg(self, reg):
        return int(self.bus.read_byte_data(self.address, reg & 0xFF))

    def _read_bytes(self, reg, length):
        if i2c_msg is not None:
            w = i2c_msg.write(self.address, [reg & 0xFF])
            r = i2c_msg.read(self.address, length)
            self.bus.i2c_rdwr(w, r)
            return list(r)

        if self._raw_i2c_fd is not None:
            try:
                return self._i2c_rdwr_ioctl(reg, length)
            except Exception:
                pass

        # fallback: one-byte smbus reads
        return [self._read_reg((reg + i) & 0xFF) for i in range(length)]

    def _i2c_rdwr_ioctl(self, reg, length):
        I2C_RDWR = 0x0707
        I2C_M_RD = 0x0001

        class _I2CMsg(ctypes.Structure):
            _fields_ = [
                ("addr", ctypes.c_uint16),
                ("flags", ctypes.c_uint16),
                ("len", ctypes.c_uint16),
                ("buf", ctypes.c_void_p),
            ]

        class _I2CRdwr(ctypes.Structure):
            _fields_ = [("msgs", ctypes.POINTER(_I2CMsg)), ("nmsgs", ctypes.c_uint32)]

        wbuf = (ctypes.c_uint8 * 1)(reg & 0xFF)
        rbuf = (ctypes.c_uint8 * length)()

        msgs = (_I2CMsg * 2)()
        msgs[0].addr = self.address
        msgs[0].flags = 0
        msgs[0].len = 1
        msgs[0].buf = ctypes.cast(wbuf, ctypes.c_void_p)

        msgs[1].addr = self.address
        msgs[1].flags = I2C_M_RD
        msgs[1].len = length
        msgs[1].buf = ctypes.cast(rbuf, ctypes.c_void_p)

        data = _I2CRdwr(msgs=msgs, nmsgs=2)
        fcntl.ioctl(self._raw_i2c_fd, I2C_RDWR, data)
        return [int(b) for b in rbuf]

    # --------------------------------------------------------------
    # QMC init and soft reset
    # --------------------------------------------------------------
    def _qmc_init(self):
        if self.chip == "QMC5883P" or self._qmc_variant == "P":
            # QMC5883P register map per QST datasheet
            self._write_reg(0x0A, 0x00)  # suspend
            time.sleep(0.005)
            try:
                self._write_reg(0x29, 0x06)  # axis sign config (recommended)
            except Exception:
                pass
            self._write_reg(0x0B, 0x08)  # set/reset on, 8G range
            time.sleep(0.001)
            self._write_reg(0x0A, 0xC3)  # continuous mode, 200Hz ODR, OSR defaults
            time.sleep(0.01)
            return

        # Legacy QMC5883L/clone sequence
        self._write_reg(0x09, 0x00)
        time.sleep(0.01)
        self._write_reg(0x0B, 0x01)
        self._write_reg(0x09, 0x1D)
        time.sleep(0.05)

    # --------------------------------------------------------------
    # RAW READ
    # --------------------------------------------------------------
    def read_raw(self):
        try:
            if self.chip in ("QMC5883L", "QMC5883P"):
                if self._qmc_variant == "P" or self.chip == "QMC5883P":
                    status = self._read_reg(0x09)
                    if status & 0x01 == 0:
                        time.sleep(0.01)
                    data = self._read_bytes(0x01, 6)
                else:
                    status = self._read_reg(0x06)
                    if status & 0x01 == 0:  # not ready
                        time.sleep(0.01)
                    data = self._read_bytes(0x00, 6)

                x = (data[1] << 8) | data[0]
                y = (data[3] << 8) | data[2]
                z = (data[5] << 8) | data[4]
            else:
                data = self._read_bytes(0x03, 6)
                x = (data[0] << 8) | data[1]
                z = (data[2] << 8) | data[3]
                y = (data[4] << 8) | data[5]

            # signed conversion
            if x > 32767:
                x -= 65536
            if y > 32767:
                y -= 65536
            if z > 32767:
                z -= 65536

            return x, y, z

        except Exception as e:
            logger.error(f"Compass read error: {e}")
            return 0, 0, 0

    # --------------------------------------------------------------
    # HEADING
    # --------------------------------------------------------------
    def _read_heading_base(self):
        """Return heading after sensor/mount calibration, before true-north mapping.

        Includes:
          - hard-iron offsets
          - soft-iron scaling
          - sensor mounting / axis heading_offset

        Excludes:
          - geographic declination
          - diagnostic correction-table mapping
        """
        if not hasattr(self, '_lock'):
            import threading
            self._lock = threading.Lock()
        with self._lock:
            x, y, _ = self.read_raw()

        if x == 0 and y == 0:
            return 0.0

        # --- Apply calibration (hard-iron + soft-iron) ---
        cx = (x - self._cal_offset_x) * self._cal_scale_x
        cy = (y - self._cal_offset_y) * self._cal_scale_y

        if cx == 0 and cy == 0:
            return 0.0

        heading_deg = math.atan2(cy, cx) * 180.0 / math.pi
        heading_deg -= self._cal_heading_offset
        heading_deg %= 360.0

        return heading_deg

    def read_heading_magnetic(self):
        """Return magnetic heading (0–360°) before true-north correction.

        This is the magnetic-north-referenced heading after magnetometer
        calibration and robot mounting alignment, but before declination or
        the optional diagnostic correction table are applied.
        """
        return self._read_heading_base()

    def read_heading(self):
        """Return the TRUE heading (0–360°) with correction applied.

        This is the corrected heading that the True North compass
        and the navigation controller use for bearing calculations.
        If no correction file exists, this falls back to simple declination
        correction on top of read_heading_magnetic().
        """
        magnetic = self.read_heading_magnetic()
        if self._correction.get("type", "none") == "none":
            return (magnetic + self.declination * 180.0 / math.pi) % 360.0
        return self.apply_correction(magnetic)

    # --------------------------------------------------------------
    # CALIBRATION
    # --------------------------------------------------------------
    def calibrate(self):
        """Legacy calibrate helper.

        This only prints rough min/max offsets and does NOT apply the
        full calibration workflow. Use your normal compass calibration
        procedure first, then run `python3 tools/compass_diagnostic.py`
        to build the magnetic -> true-heading correction table.
        """
        logger.info("Rotate compass 360° for 30 seconds")

        min_x = 99999
        max_x = -99999
        min_y = 99999
        max_y = -99999

        t0 = time.time()
        while time.time() - t0 < 30:
            x, y, _ = self.read_raw()
            min_x = min(min_x, x)
            max_x = max(max_x, x)
            min_y = min(min_y, y)
            max_y = max(max_y, y)
            time.sleep(0.1)

        off_x = (max_x + min_x) / 2
        off_y = (max_y + min_y) / 2
        logger.info(f"Offsets: X={off_x:.1f}, Y={off_y:.1f}")
        logger.info("For full calibration, use the project compass calibration workflow, then run: python3 tools/compass_diagnostic.py")

        logger.info(f"Calibration offsets: X={off_x}, Y={off_y}")
        return off_x, off_y
